/*
 * samples.js - the two reference papers, transcribed as typed (inconsistencies
 * and all) so the formatter can be tried out without a file at hand.
 */
(function (PF) {
  'use strict';

  var HINDI = [
    'S.S. ACADEMY KOIRAUNA BHADOHI',
    'Half yearly examination 2026-27',
    'Sub:- Hindi',
    'Time- 2:30    Class:- 5th    M.M. 50',
    'प्रश्न-1. सही विकल्प के सामने (✓) का चिन्ह लगाइए- (5)',
    'क) हमारी राष्ट्रभाषा है-',
    '(अ) पंजाबी ( )    (ब) हिंदी ( )    (स) उर्दू ( )',
    'ख) ठंडा प्रदेश है-',
    '(अ) उत्तर प्रदेश ( )    (ब) मुंबई ( )    (स) कश्मीर ( )',
    'ग) भारत की पवित्र नदियाँ हैं-',
    '(अ) गंगा ( )    (ब) यमुना ( )    (स) गंगा व यमुना दोनों ( )',
    'घ) सबसे अधिक वर्षा कहाँ होती है?',
    '(अ) कश्मीर में ( )    (ब) चेरापूंजी में ( )    (स) केरल में ( )',
    'प्रश्न 2. रिक्त स्थानों की पूर्ति कीजिए— (5)',
    'क) कक्षाओं में भी विद्यार्थियों को इसमें ______ किया जा रहा है।',
    'ख) मानव की ______ में कंप्यूटर का बहुत बड़ा योगदान है।',
    'ग) जीवन के हर क्षेत्र में कंप्यूटर ______ कर रहा है।',
    'घ) आज जगह-जगह कंप्यूटर ______ खुल रहे हैं।',
    'प्रश्न-3. निम्नलिखित प्रश्नों के उत्तर दीजिए- (5)',
    '1. अश्वमेध महायज्ञ किसने किया था?',
    '2. ‘एक बूँद’ कविता के कवि कौन हैं?',
    '3. मिर्ची ने गिरगिट को किस शब्द से संबोधित किया?',
    '4. कीटाणु कहाँ रहते हैं?',
    '5. लालची रीछ कहाँ रहता था?',
    'प्रश्न 4. उचित मिलान कीजिए- (5)',
    'कॉलम ‘क’    कॉलम ‘ख’',
    '(क) चिरायु    उचित मात्रा में होना',
    '(ख) पीढ़ियाँ    रक्षा के लिए पुकारा',
    '(ग) संतुलन    वंशक्रम की कड़ियाँ',
    '(घ) त्राहि-त्राहि    लंबी आयु',
    'प्रश्न 5. अपनी पाठ्य पुस्तक के आधार पर 8 लाइन की कविता लिखिए? (5)',
    'प्रश्न 6. निम्नलिखित प्रश्नों के उत्तर दीजिए- (5)',
    'क) वर्ण किसे कहते हैं?',
    'ख) स्त्रीलिंग किसे कहते हैं? उदाहरण सहित लिखिए।',
    'ग) वचन किसे कहते हैं?',
    'घ) व्याकरण किसे कहते हैं?',
    'प्रश्न 7. शब्दार्थ लिखिए? (5)',
    '1. चिरायु    2. परजीवी    3. दरिद्र    4. समाधान    5. भाग्य',
    'प्रश्न 8. अवकाश के लिए प्रार्थना पत्र लिखिए? (5)',
    'प्रश्न 9. अपने विद्यालय अथवा प्रदूषण पर निबंध लिखिए? (5)',
    'प्रश्न 10. विलोम शब्द लिखिए- (2)',
    '1. प्राचीन    2. कम    3. पवित्र    4. प्रेम    5. गर्म',
    'प्रश्न 11. निम्नलिखित शब्दों के दो-दो पर्यायवाची शब्द लिखिए- (3)',
    '1. पेड़    2. मित्र    3. पुष्प    4. पृथ्वी    5. जल'
  ].join('\n');

  var ENGLISH = [
    'S.S. ACADEMY KOIRAUNA BHADOHI',
    'HALF YEARLY EXAMINATION 2026 -27',
    'Sub - English',
    'Time - 2:30 h    Class - 2nd (B)    M.M.50',
    'QUE - 1 Tick the correct option (5)',
    '1 . Toto was a little',
    'A . Bug ( )  B bird ( )  C Tortoise ( )',
    '2. The tortoise loves',
    'A. Sweet ( ) B. Maggi ( ) C. Fruits ( ) D. Chocolate ( )',
    '3. Too Many sweets spoils our',
    'a. Tongue ( ) b. Teeth ( ) c. Lungs ( ) d. Sight ( )',
    'Que -2 Fill in the blanks (5)',
    '1. Ella had two _______ as friends.',
    '2. When ella felt tried she went to leave under a_______',
    '3. The first egret stroked ella  ahead with his ______',
    '4. The young elephant brought_________ for ella',
    '5. Ella felt better the next __________',
    'Que-3 write true and false statement (5)',
    '1. Toto the little tortoise loves sweets [ ]',
    '2. Toto does not have a two headache [ ]',
    '3. The doctor advice toto eat more sweets [ ]',
    '4. The doctor tell toto brush is teeth two times everyday [ ]',
    'Que - 4 Answer the following questions(10)',
    '1. Who was inky ?',
    '2. Did Alexander like the horse very much ?',
    '3. Who was Swamiji and how many disciples did he had?',
    '4. Did Ella have two greats as friends ?',
    '5. What happened to Toto ?',
    'Que -5 Complete the spellings (5)',
    '1. M_ n_e _',
    '2. P_a_',
    '3. W_s_o_',
    '4. G_o_ y',
    '5. G_i_e',
    '6. T_o_s_n_',
    '7. N_g_t',
    '8. B_n_n_',
    '9. L_g_t',
    '10. P_ w _ r',
    'Que _6 Match the following opposite words (5)',
    '1. Buy      tight',
    '2. Empty    Flood',
    '3. Loose    full',
    '4. Selfish  selfless',
    '5. Brought  sell',
    'Que -7 write word meanings(5)',
    '1. Bright',
    '2. friend',
    '3. Sweet',
    '4. Book',
    '5. God',
    'Que -8 write 8 line poems ?(5)',
    'Que- 9 Write the plurals of the given words(5)',
    '1. Tiger   2. Pen   3. Boat   4. Boy   5. Paper'
  ].join('\n');

  PF.samples = { hindi: HINDI, english: ENGLISH };
})(window.PF = window.PF || {});
